version: '1'
services:
  health-api:
    image: node:18
    container_name: mintlayer_health
    volumes:
      - ./health-api:/app
    working_dir: /app
    command: node index.js
    ports:
      - "3033:3033" # external mapping
    restart: unless-stopped
